apiVersion: kubeflow.org/v1alpha2
kind: TFJob
metadata:
  name: training#{Build.BuildId}#
spec:
  tfReplicaSpecs:
    MASTER:
      replicas: 1
      template:
        spec:
          containers:
            # image contains model which will be trained here
            - image: danielmeixner/#{modelname}#:#{Build.BuildId}#
              name: tensorflow             
              volumeMounts:                
                - name: azurefile                  
                  subPath: trainedmodels/trainedmodel#{Build.BuildId}#      
                  mountPath: /tmp/tensorflow                
          restartPolicy: OnFailure
          volumes:
            - name: azurefile
              persistentVolumeClaim:
                claimName: azurefile
